-- ============================================================
-- Seed: Crop-specific soil sufficiency overrides
-- Only parameters that differ from universal defaults
-- ============================================================

INSERT INTO crop_sufficiency_overrides (crop, parameter, very_low_max, low_max, optimal_max, high_max, notes)
VALUES
-- Blueberry: acidophilic crop, requires very low pH and low Ca
('Blueberry', 'pH (KCl)', 3.8, 4.2, 5.5, 6.0, 'Acidophilic crop; optimal pH 4.5-5.5 KCl. Above 5.5 induces iron chlorosis.'),
('Blueberry', 'pH (H2O)', 4.3, 4.7, 6.0, 6.5, 'Acidophilic crop; optimal pH 5.0-5.8 H2O.'),
('Blueberry', 'Ca', 150, 300, 1200, 2500, 'Tolerates and prefers lower Ca; high Ca raises pH and impairs Fe/Mn uptake.'),
('Pineapple', 'pH (KCl)', 3.8, 4.2, 5.5, 6.0, 'Acidophilic crop; optimal pH 4.5-5.5 KCl.'),
('Pineapple', 'pH (H2O)', 4.3, 4.7, 6.0, 6.5, 'Acidophilic crop; optimal pH 5.0-6.0 H2O.'),
('Tea', 'pH (KCl)', 3.8, 4.2, 5.5, 6.0, 'Acidophilic crop; optimal pH 4.5-5.5 KCl. Aluminium tolerant.'),
('Tea', 'pH (H2O)', 4.3, 4.7, 6.0, 6.5, 'Acidophilic crop; optimal pH 5.0-5.8 H2O.'),
('Rooibos', 'pH (KCl)', 3.8, 4.2, 5.5, 6.0, 'Fynbos species; prefers acid soils, pH 4.5-5.5 KCl.'),
('Rooibos', 'pH (H2O)', 4.3, 4.7, 6.0, 6.5, 'Fynbos species; optimal pH 5.0-6.0 H2O.'),
('Rooibos', 'P (Bray-1)', 2, 5, 12, 25, 'Proteaceae-type root system; P-sensitive. Excess P is toxic.'),
('Potato', 'pH (KCl)', 4.0, 4.5, 5.5, 6.5, 'Lower pH (4.8-5.5) reduces common scab incidence.'),
('Potato', 'pH (H2O)', 4.5, 5.0, 6.0, 7.0, 'Lower pH reduces common scab incidence.'),
('Potato', 'P (Bray-1)', 8, 20, 35, 60, 'High P feeder; tuber initiation and bulking require ample P.'),
('Strawberry', 'pH (KCl)', 4.2, 4.8, 5.8, 6.5, 'Prefers slightly acid soil; optimal pH 5.0-5.8 KCl.'),
('Strawberry', 'pH (H2O)', 4.7, 5.3, 6.3, 7.0, 'Prefers slightly acid soil; optimal pH 5.5-6.3 H2O.'),
('Coffee', 'pH (KCl)', 4.2, 4.8, 5.8, 6.5, 'Prefers slightly acid soil; optimal pH 5.0-5.8 KCl.'),
('Coffee', 'pH (H2O)', 4.7, 5.3, 6.3, 7.0, 'Prefers slightly acid soil; optimal pH 5.5-6.3 H2O.'),
('Lucerne', 'pH (KCl)', 5.0, 5.5, 6.8, 7.5, 'Requires higher pH (5.8-6.8 KCl) for Rhizobium nodulation and Mo availability.'),
('Lucerne', 'pH (H2O)', 5.5, 6.0, 7.3, 8.0, 'Requires higher pH for nodulation; sensitive to acid soils.'),
('Lucerne', 'B', 0.3, 0.8, 1.5, 2.5, 'High B requirement; B deficiency causes yellowing and poor regrowth.'),
('Banana', 'K', 80, 150, 300, 500, 'Very high K feeder; K critical for bunch weight and fruit quality.'),
('Grape (Wine)', 'K', 30, 60, 160, 300, 'Excess K raises juice pH, reducing wine quality. Moderate K preferred.'),
('Citrus', 'Mg', 80, 150, 400, 700, 'Higher Mg requirement; Mg deficiency common in SA citrus orchards.'),
('Maize', 'Zn', 0.8, 2.0, 6.0, 12.0, 'Zn-sensitive crop; Zn deficiency widespread in SA maize production.'),
('Pecan', 'Zn', 1.0, 2.5, 7.0, 12.0, 'Very high Zn requirement; most common nutritional disorder in pecans.'),
('Pecan', 'B', 0.3, 0.8, 1.5, 2.5, 'Elevated B requirement for nut fill and kernel quality.'),
('Macadamia', 'Zn', 0.8, 2.0, 6.0, 12.0, 'Elevated Zn requirement for nut development and tree health.'),
('Macadamia', 'B', 0.3, 0.8, 1.5, 2.5, 'Elevated B requirement; B deficiency causes blank nuts and poor set.'),
('Sunflower', 'B', 0.3, 0.8, 1.5, 2.5, 'High B requirement; B deficiency causes hollow stem and poor head fill.'),
('Cabbage', 'B', 0.3, 0.8, 1.5, 2.5, 'High B requirement; B deficiency causes hollow stem.'),
('Canola', 'B', 0.3, 0.8, 1.5, 2.5, 'High B requirement; B deficiency causes flower sterility.'),
('Tomato', 'Ca', 300, 700, 2500, 5000, 'High Ca requirement; adequate soil Ca reduces blossom end rot.'),
('Apple', 'Ca', 300, 700, 2500, 5000, 'Higher Ca threshold for fruit quality; Ca prevents bitter pit.'),
('Pear', 'Ca', 300, 700, 2500, 5000, 'Higher Ca threshold; Ca prevents cork spot and internal breakdown.'),
('Pepper (Bell)', 'Ca', 300, 700, 2500, 5000, 'High Ca requirement; reduces blossom end rot.'),
('Groundnut', 'Ca', 300, 800, 2500, 5000, 'High Ca in pegging zone for proper pod fill. Critical for kernel quality.'),
('Avocado', 'B', 0.3, 0.8, 1.5, 2.5, 'Higher B requirement; B deficiency causes misshapen fruit.'),
('Sugarcane', 'K', 60, 120, 250, 450, 'High K feeder; K important for sucrose accumulation.'),
('Soybean', 'pH (KCl)', 4.8, 5.3, 6.3, 7.2, 'Higher pH preferred for Bradyrhizobium nodulation.'),
('Soybean', 'pH (H2O)', 5.3, 5.8, 6.8, 7.7, 'Higher pH preferred for nodulation and nutrient availability.'),
('Wheat', 'Zn', 0.8, 2.0, 6.0, 12.0, 'Elevated Zn requirement; Zn deficiency common in SA wheat soils.'),
('Cotton', 'K', 60, 120, 250, 450, 'High K feeder; K deficiency causes premature leaf drop and poor fibre.'),
('Tobacco', 'pH (KCl)', 4.2, 4.8, 5.8, 6.5, 'Prefers slightly acid soil; optimal pH 5.0-5.8 KCl.'),
('Tobacco', 'pH (H2O)', 4.7, 5.3, 6.3, 7.0, 'Prefers slightly acid soil for optimal nutrient balance.'),
('Olive', 'pH (KCl)', 5.0, 5.5, 6.8, 7.5, 'Tolerates and prefers higher pH; performs well in calcareous soils.'),
('Olive', 'pH (H2O)', 5.5, 6.0, 7.3, 8.0, 'Tolerates higher pH; adapted to Mediterranean calcareous soils.'),
('Olive', 'B', 0.3, 0.8, 1.5, 2.5, 'Elevated B requirement; B deficiency causes monkey-face fruit deformity.'),
('Litchi', 'pH (KCl)', 4.2, 4.8, 5.8, 6.5, 'Prefers slightly acid soil; optimal pH 5.0-5.8 KCl.'),
('Litchi', 'Zn', 0.8, 2.0, 6.0, 12.0, 'Elevated Zn requirement for fruit set and leaf health.');
